apiVersion : apps/v1
kind: Deployment
metadata:
  name: "kubernetesdemo-ff01"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "kubernetesdemo-ff01"
  template:
    metadata:
      labels:
        app: "kubernetesdemo-ff01"
    spec:
      containers:
        - name: "kubernetesdemo-ff01"
          image: "mynewregistryy.azurecr.io/kubernetesdemo"
          ports:
          - containerPort: 3000