apiVersion: v1
kind: Service
metadata:
    name: "kubernetesdemo-ff01"
    labels:
        app: "kubernetesdemo-ff01"
spec:
    type: LoadBalancer
    ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
    selector:
        app: "kubernetesdemo-ff01"